
GET http://localhost:9200/lyci/article/_mget
Content-Type: application/json

{
"docs": [
  {
    "_id": 1
  },
  {
    "_id": 2
  },
  {
    "_id": 3
  }
]
}

###

POST http://localhost:9200/lyci/article/4?version=7&version_type=external
Content-Type: application/json

{
  "title": "三国演义",
  "author": "罗贯中",
  "price": 100
}

###























